// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSecurityRole = `-- name: CreateSecurityRole :one
INSERT INTO security_roles(
    role_uuid,
    role_name,
    created_at
) VALUES ($1,$2,$3) RETURNING role_id
`

type CreateSecurityRoleParams struct {
	RoleUuid  uuid.UUID
	RoleName  string
	CreatedAt time.Time
}

func (q *Queries) CreateSecurityRole(ctx context.Context, arg CreateSecurityRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSecurityRole, arg.RoleUuid, arg.RoleName, arg.CreatedAt)
	var role_id int64
	err := row.Scan(&role_id)
	return role_id, err
}

const createSecurityRolePermission = `-- name: CreateSecurityRolePermission :exec
INSERT INTO security_role_permissions(
    role_id,
    permission_id,
    created_at
) VALUES ($1,$2,$3)
`

type CreateSecurityRolePermissionParams struct {
	RoleID       int64
	PermissionID int64
	CreatedAt    time.Time
}

func (q *Queries) CreateSecurityRolePermission(ctx context.Context, arg CreateSecurityRolePermissionParams) error {
	_, err := q.db.Exec(ctx, createSecurityRolePermission, arg.RoleID, arg.PermissionID, arg.CreatedAt)
	return err
}

const getPermissions = `-- name: GetPermissions :many
SELECT permission_id,
    permission_uuid,
    permission_name,
    permission_type,
    permission_value,
    created_at,
    updated_at
FROM security_permissions
WHERE permission_id = ANY($1::bigint[])
`

type GetPermissionsRow struct {
	PermissionID    int64
	PermissionUuid  uuid.UUID
	PermissionName  string
	PermissionType  string
	PermissionValue string
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
}

func (q *Queries) GetPermissions(ctx context.Context, dollar_1 []int64) ([]GetPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getPermissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionsRow
	for rows.Next() {
		var i GetPermissionsRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.PermissionUuid,
			&i.PermissionName,
			&i.PermissionType,
			&i.PermissionValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsByUUID = `-- name: GetPermissionsByUUID :many
SELECT permission_id,
    permission_uuid,
    permission_name,
    permission_type,
    permission_value,
    created_at,
    updated_at
FROM security_permissions
WHERE permission_uuid = ANY($1::uuid[])
`

type GetPermissionsByUUIDRow struct {
	PermissionID    int64
	PermissionUuid  uuid.UUID
	PermissionName  string
	PermissionType  string
	PermissionValue string
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
}

func (q *Queries) GetPermissionsByUUID(ctx context.Context, dollar_1 []uuid.UUID) ([]GetPermissionsByUUIDRow, error) {
	rows, err := q.db.Query(ctx, getPermissionsByUUID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionsByUUIDRow
	for rows.Next() {
		var i GetPermissionsByUUIDRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.PermissionUuid,
			&i.PermissionName,
			&i.PermissionType,
			&i.PermissionValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecurityRolePermissions = `-- name: GetSecurityRolePermissions :many
SELECT srp.role_id,
    sr.role_name,
    sp.permission_id,
    sp.permission_uuid,
    sp.permission_name,
    sp.permission_type,
    sp.permission_key,
    sp.permission_value
FROM security_roles sr,
    security_permissions sp,
    security_role_permissions srp
WHERE sr.role_id = $1
    AND sr.role_id = srp.role_id
    AND srp.permission_id = sp.permission_id
ORDER by srp.role_id, srp.permission_id
`

type GetSecurityRolePermissionsRow struct {
	RoleID          int64
	RoleName        string
	PermissionID    int64
	PermissionUuid  uuid.UUID
	PermissionName  string
	PermissionType  string
	PermissionKey   string
	PermissionValue string
}

func (q *Queries) GetSecurityRolePermissions(ctx context.Context, roleID int64) ([]GetSecurityRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getSecurityRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSecurityRolePermissionsRow
	for rows.Next() {
		var i GetSecurityRolePermissionsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleName,
			&i.PermissionID,
			&i.PermissionUuid,
			&i.PermissionName,
			&i.PermissionType,
			&i.PermissionKey,
			&i.PermissionValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
