// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: types/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSessionType int32

const (
	UserSessionType_USER_SESSION_TYPE_UNSPECIFIED   UserSessionType = 0
	UserSessionType_USER_SESSION_TYPE_GUEST         UserSessionType = 1
	UserSessionType_USER_SESSION_TYPE_AUTHENTICATED UserSessionType = 10
)

// Enum value maps for UserSessionType.
var (
	UserSessionType_name = map[int32]string{
		0:  "USER_SESSION_TYPE_UNSPECIFIED",
		1:  "USER_SESSION_TYPE_GUEST",
		10: "USER_SESSION_TYPE_AUTHENTICATED",
	}
	UserSessionType_value = map[string]int32{
		"USER_SESSION_TYPE_UNSPECIFIED":   0,
		"USER_SESSION_TYPE_GUEST":         1,
		"USER_SESSION_TYPE_AUTHENTICATED": 10,
	}
)

func (x UserSessionType) Enum() *UserSessionType {
	p := new(UserSessionType)
	*p = x
	return p
}

func (x UserSessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_user_user_proto_enumTypes[0].Descriptor()
}

func (UserSessionType) Type() protoreflect.EnumType {
	return &file_types_user_user_proto_enumTypes[0]
}

func (x UserSessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSessionType.Descriptor instead.
func (UserSessionType) EnumDescriptor() ([]byte, []int) {
	return file_types_user_user_proto_rawDescGZIP(), []int{0}
}

type UserSecretType int32

const (
	UserSecretType_USER_SECRET_TYPE_UNSPECIFIED UserSecretType = 0
	UserSecretType_USER_SECRET_TYPE_PASSWORD    UserSecretType = 1
	UserSecretType_USER_SECRET_TYPE_API_TOKEN   UserSecretType = 20
	UserSecretType_USER_SECRET_TYPE_USER_PIN    UserSecretType = 30
)

// Enum value maps for UserSecretType.
var (
	UserSecretType_name = map[int32]string{
		0:  "USER_SECRET_TYPE_UNSPECIFIED",
		1:  "USER_SECRET_TYPE_PASSWORD",
		20: "USER_SECRET_TYPE_API_TOKEN",
		30: "USER_SECRET_TYPE_USER_PIN",
	}
	UserSecretType_value = map[string]int32{
		"USER_SECRET_TYPE_UNSPECIFIED": 0,
		"USER_SECRET_TYPE_PASSWORD":    1,
		"USER_SECRET_TYPE_API_TOKEN":   20,
		"USER_SECRET_TYPE_USER_PIN":    30,
	}
)

func (x UserSecretType) Enum() *UserSecretType {
	p := new(UserSecretType)
	*p = x
	return p
}

func (x UserSecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_user_user_proto_enumTypes[1].Descriptor()
}

func (UserSecretType) Type() protoreflect.EnumType {
	return &file_types_user_user_proto_enumTypes[1]
}

func (x UserSecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSecretType.Descriptor instead.
func (UserSecretType) EnumDescriptor() ([]byte, []int) {
	return file_types_user_user_proto_rawDescGZIP(), []int{1}
}

var File_types_user_user_proto protoreflect.FileDescriptor

var file_types_user_user_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2a, 0x76,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x21, 0x0a, 0x1d, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x55, 0x45, 0x53, 0x54, 0x10,
	0x01, 0x12, 0x23, 0x0a, 0x1f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x0a, 0x2a, 0x90, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41,
	0x50, 0x49, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x14, 0x12, 0x1d, 0x0a, 0x19, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x50, 0x49, 0x4e, 0x10, 0x1e, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2d, 0x61,
	0x73, 0x64, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_types_user_user_proto_rawDescOnce sync.Once
	file_types_user_user_proto_rawDescData []byte
)

func file_types_user_user_proto_rawDescGZIP() []byte {
	file_types_user_user_proto_rawDescOnce.Do(func() {
		file_types_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_user_user_proto_rawDesc), len(file_types_user_user_proto_rawDesc)))
	})
	return file_types_user_user_proto_rawDescData
}

var file_types_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_user_user_proto_goTypes = []any{
	(UserSessionType)(0), // 0: go_example.types.user.UserSessionType
	(UserSecretType)(0),  // 1: go_example.types.user.UserSecretType
}
var file_types_user_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_user_user_proto_init() }
func file_types_user_user_proto_init() {
	if File_types_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_user_user_proto_rawDesc), len(file_types_user_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_user_user_proto_goTypes,
		DependencyIndexes: file_types_user_user_proto_depIdxs,
		EnumInfos:         file_types_user_user_proto_enumTypes,
	}.Build()
	File_types_user_user_proto = out.File
	file_types_user_user_proto_goTypes = nil
	file_types_user_user_proto_depIdxs = nil
}
