// Code is generated by helper script. DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"log"
	"os"
	"testing"
	"time"
)

var (
	testCtx context.Context
	testHelper *TestHelper
)

func TestMain(m *testing.M) {
	var cancel context.CancelFunc
	testCtx, cancel = context.WithTimeout(context.Background(), time.Minute*5)
	code, err := run(testCtx, m)
	if err != nil {
		log.Println(err)
	}
	cancel()
	os.Exit(code)
}

func run(ctx context.Context, m *testing.M) (code int, err error) {
	testHelper, err = NewTestHelper(ctx)
	if err != nil {
		code = 1
		return
	}
	// Close all resources upon exit, and record the error when closing the resources if any.
	defer func() {
		errClose := testHelper.Close()
		if errClose != nil {
			err = errors.Join(err, errClose)
		}
	}()
	code = m.Run()
	return
}

