// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"database/sql"
	"time"
)

type LedgerAccount struct {
	AccountID       string
	Name            string
	Description     string
	ParentAccountID sql.NullString
	CurrencyID      int32
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
}

type LedgerMovement struct {
	MovementID         string
	IdempotencyKey     string
	CreatedAt          time.Time
	UpdatedAt          sql.NullTime
	ReversedAt         sql.NullTime
	ReversalMovementID sql.NullString
}
