// Code is generated by helper script. DO NOT EDIT.

package postgres

import (
	"context"
	"log"
	"os"
	"testing"
	"time"

	"github.com/albertwidi/pkg/postgres"
	"github.com/albertwidi/pkg/testing/pgtest"
)

var (
	testPG *postgres.Postgres
	testQueries *Queries
	testHelper *pgtest.PGTest
	testCtx context.Context
)

func TestMain(m *testing.M) {
	var cancel context.CancelFunc
	testCtx, cancel = context.WithTimeout(context.Background(), time.Minute*5)
	code, err := run(testCtx, m)
	if err != nil {
		log.Println(err)
	}
	cancel()
	os.Exit(code)
}

func run(ctx context.Context, m *testing.M) (int, error) {
	var err error
	testPG, err = PrepareTest(ctx)
	if err != nil {
		return 1, err
	}
	testQueries = New(testPG)
	testHelper = pgtest.New()
	return m.Run(), nil
}
