services:
  postgres:
    container_name: sqlc-postgres
    image: library/postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: GMT
    volumes:
      - ./schemas:/data
