// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"database/sql"
	"time"
)

type User struct {
	UserID     int64
	ExternalID string
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
}

type UserPii struct {
	UserID         int64
	Email          string
	PhoneNumber    sql.NullString
	IdentityNumber sql.NullString
	IdentityType   sql.NullInt32
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
}

type UserSecret struct {
	SecretID             int64
	ExternalID           string
	UserID               int64
	SecretKey            string
	SecretType           int32
	CurrentSecretVersion int64
	CreatedAt            time.Time
	UpdatedAt            sql.NullTime
}
