// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"database/sql"
	"net/netip"
	"time"
)

type UserSecret struct {
	SecretID             int64
	ExternalID           string
	UserID               int64
	SecretKey            string
	SecretType           int32
	CurrentSecretVersion int64
	CreatedAt            time.Time
	UpdatedAt            sql.NullTime
}

type UserSession struct {
	UserID               int64
	RandomNumber         int32
	CreatedTime          int64
	CreatedFromIp        netip.Addr
	CreatedFromLoc       sql.NullString
	CreatedFromUserAgent string
	SessionMetadata      []byte
	ExpiredAt            time.Time
}
