// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"time"
)

type UserDataUserSession struct {
	UserID          int64
	RandomNumber    int32
	CreatedTime     int64
	SessionMetadata []byte
	ExpiredAt       time.Time
}
