// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package postgres

import (
	"context"
	"time"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallet_accounts(
	wallet_id,
	ledger_account_id,
	user_id,
	wallet_status,
	wallet_type,
	created_at
) VALUES($1,$2,$3,$4,$5, $6)
`

type CreateWalletParams struct {
	WalletID        string
	LedgerAccountID string
	UserID          string
	WalletStatus    int32
	WalletType      int32
	CreatedAt       time.Time
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.Exec(ctx, createWallet,
		arg.WalletID,
		arg.LedgerAccountID,
		arg.UserID,
		arg.WalletStatus,
		arg.WalletType,
		arg.CreatedAt,
	)
	return err
}
