// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/ledger/v1/account.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLedgerAccountsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts []*CreateLedgerAccountsRequest_CreateAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (x *CreateLedgerAccountsRequest) Reset() {
	*x = CreateLedgerAccountsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLedgerAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerAccountsRequest) ProtoMessage() {}

func (x *CreateLedgerAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerAccountsRequest.ProtoReflect.Descriptor instead.
func (*CreateLedgerAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLedgerAccountsRequest) GetAccounts() []*CreateLedgerAccountsRequest_CreateAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type CreateLedgerAccountsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts []*CreateLedgerAccountsResponse_CreateAccountResponse `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (x *CreateLedgerAccountsResponse) Reset() {
	*x = CreateLedgerAccountsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLedgerAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerAccountsResponse) ProtoMessage() {}

func (x *CreateLedgerAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerAccountsResponse.ProtoReflect.Descriptor instead.
func (*CreateLedgerAccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLedgerAccountsResponse) GetAccounts() []*CreateLedgerAccountsResponse_CreateAccountResponse {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type CreateLedgerAccountsRequest_CreateAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentAccountId string `protobuf:"bytes,1,opt,name=parent_account_id,json=parentAccountId,proto3" json:"parent_account_id,omitempty"`
	AllowNegative   bool   `protobuf:"varint,2,opt,name=allow_negative,json=allowNegative,proto3" json:"allow_negative,omitempty"`
	CurrencyId      int32  `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
}

func (x *CreateLedgerAccountsRequest_CreateAccount) Reset() {
	*x = CreateLedgerAccountsRequest_CreateAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLedgerAccountsRequest_CreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerAccountsRequest_CreateAccount) ProtoMessage() {}

func (x *CreateLedgerAccountsRequest_CreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerAccountsRequest_CreateAccount.ProtoReflect.Descriptor instead.
func (*CreateLedgerAccountsRequest_CreateAccount) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_account_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateLedgerAccountsRequest_CreateAccount) GetParentAccountId() string {
	if x != nil {
		return x.ParentAccountId
	}
	return ""
}

func (x *CreateLedgerAccountsRequest_CreateAccount) GetAllowNegative() bool {
	if x != nil {
		return x.AllowNegative
	}
	return false
}

func (x *CreateLedgerAccountsRequest_CreateAccount) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

type CreateLedgerAccountsResponse_CreateAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CreateLedgerAccountsResponse_CreateAccountResponse) Reset() {
	*x = CreateLedgerAccountsResponse_CreateAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLedgerAccountsResponse_CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerAccountsResponse_CreateAccountResponse) ProtoMessage() {}

func (x *CreateLedgerAccountsResponse_CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerAccountsResponse_CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateLedgerAccountsResponse_CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_account_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateLedgerAccountsResponse_CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateLedgerAccountsResponse_CreateAccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_ledger_v1_account_proto protoreflect.FileDescriptor

var file_api_ledger_v1_account_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x67,
	0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5f, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0x93, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6e, 0x65,
	0x67, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42, 0x06, 0xba, 0x48,
	0x03, 0xc8, 0x01, 0x01, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x4e, 0x65, 0x67, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x27, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01,
	0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x22, 0xfb, 0x01, 0x0a,
	0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a,
	0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x4c, 0x2e, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0x71, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x62, 0x65, 0x72, 0x74, 0x77,
	0x69, 0x64, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ledger_v1_account_proto_rawDescOnce sync.Once
	file_api_ledger_v1_account_proto_rawDescData = file_api_ledger_v1_account_proto_rawDesc
)

func file_api_ledger_v1_account_proto_rawDescGZIP() []byte {
	file_api_ledger_v1_account_proto_rawDescOnce.Do(func() {
		file_api_ledger_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ledger_v1_account_proto_rawDescData)
	})
	return file_api_ledger_v1_account_proto_rawDescData
}

var file_api_ledger_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_ledger_v1_account_proto_goTypes = []any{
	(*CreateLedgerAccountsRequest)(nil),                        // 0: go_example.api.ledger.v1.CreateLedgerAccountsRequest
	(*CreateLedgerAccountsResponse)(nil),                       // 1: go_example.api.ledger.v1.CreateLedgerAccountsResponse
	(*CreateLedgerAccountsRequest_CreateAccount)(nil),          // 2: go_example.api.ledger.v1.CreateLedgerAccountsRequest.CreateAccount
	(*CreateLedgerAccountsResponse_CreateAccountResponse)(nil), // 3: go_example.api.ledger.v1.CreateLedgerAccountsResponse.CreateAccountResponse
	(*timestamppb.Timestamp)(nil),                              // 4: google.protobuf.Timestamp
}
var file_api_ledger_v1_account_proto_depIdxs = []int32{
	2, // 0: go_example.api.ledger.v1.CreateLedgerAccountsRequest.accounts:type_name -> go_example.api.ledger.v1.CreateLedgerAccountsRequest.CreateAccount
	3, // 1: go_example.api.ledger.v1.CreateLedgerAccountsResponse.accounts:type_name -> go_example.api.ledger.v1.CreateLedgerAccountsResponse.CreateAccountResponse
	4, // 2: go_example.api.ledger.v1.CreateLedgerAccountsResponse.CreateAccountResponse.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_ledger_v1_account_proto_init() }
func file_api_ledger_v1_account_proto_init() {
	if File_api_ledger_v1_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ledger_v1_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLedgerAccountsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLedgerAccountsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_account_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLedgerAccountsRequest_CreateAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_account_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLedgerAccountsResponse_CreateAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ledger_v1_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ledger_v1_account_proto_goTypes,
		DependencyIndexes: file_api_ledger_v1_account_proto_depIdxs,
		MessageInfos:      file_api_ledger_v1_account_proto_msgTypes,
	}.Build()
	File_api_ledger_v1_account_proto = out.File
	file_api_ledger_v1_account_proto_rawDesc = nil
	file_api_ledger_v1_account_proto_goTypes = nil
	file_api_ledger_v1_account_proto_depIdxs = nil
}
