// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/ledger/v1/ledger.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey  string           `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MovementEntries []*MovementEntry `protobuf:"bytes,2,rep,name=movement_entries,json=movementEntries,proto3" json:"movement_entries,omitempty"`
}

func (x *TransactRequest) Reset() {
	*x = TransactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactRequest) ProtoMessage() {}

func (x *TransactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactRequest.ProtoReflect.Descriptor instead.
func (*TransactRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *TransactRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransactRequest) GetMovementEntries() []*MovementEntry {
	if x != nil {
		return x.MovementEntries
	}
	return nil
}

type TransactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovementId string   `protobuf:"bytes,1,opt,name=movement_id,json=movementId,proto3" json:"movement_id,omitempty"`
	LedgerIds  []string `protobuf:"bytes,2,rep,name=ledger_ids,json=ledgerIds,proto3" json:"ledger_ids,omitempty"`
}

func (x *TransactResponse) Reset() {
	*x = TransactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse) ProtoMessage() {}

func (x *TransactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse.ProtoReflect.Descriptor instead.
func (*TransactResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransactResponse) GetMovementId() string {
	if x != nil {
		return x.MovementId
	}
	return ""
}

func (x *TransactResponse) GetLedgerIds() []string {
	if x != nil {
		return x.LedgerIds
	}
	return nil
}

type MovementEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAccountId string `protobuf:"bytes,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string `protobuf:"bytes,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MovementEntry) Reset() {
	*x = MovementEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementEntry) ProtoMessage() {}

func (x *MovementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementEntry.ProtoReflect.Descriptor instead.
func (*MovementEntry) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *MovementEntry) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *MovementEntry) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *MovementEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_api_ledger_v1_ledger_proto protoreflect.FileDescriptor

var file_api_ledger_v1_ledger_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x67, 0x6f,
	0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6d, 0x70,
	0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f,
	0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x5a, 0x0a, 0x10, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x06, 0xba, 0x48, 0x03,
	0xc8, 0x01, 0x01, 0x52, 0x0f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x0f, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0d, 0x66, 0x72, 0x6f,
	0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x0d, 0x74, 0x6f,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0b, 0x74, 0x6f, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x62, 0x65, 0x72, 0x74, 0x77, 0x69, 0x64, 0x69, 0x2f,
	0x67, 0x6f, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_api_ledger_v1_ledger_proto_rawDescData = file_api_ledger_v1_ledger_proto_rawDesc
)

func file_api_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_api_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_api_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ledger_v1_ledger_proto_rawDescData)
	})
	return file_api_ledger_v1_ledger_proto_rawDescData
}

var file_api_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_ledger_v1_ledger_proto_goTypes = []any{
	(*TransactRequest)(nil),  // 0: go_example.api.ledger.v1.TransactRequest
	(*TransactResponse)(nil), // 1: go_example.api.ledger.v1.TransactResponse
	(*MovementEntry)(nil),    // 2: go_example.api.ledger.v1.MovementEntry
}
var file_api_ledger_v1_ledger_proto_depIdxs = []int32{
	2, // 0: go_example.api.ledger.v1.TransactRequest.movement_entries:type_name -> go_example.api.ledger.v1.MovementEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ledger_v1_ledger_proto_init() }
func file_api_ledger_v1_ledger_proto_init() {
	if File_api_ledger_v1_ledger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ledger_v1_ledger_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TransactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TransactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MovementEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ledger_v1_ledger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_api_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_api_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_api_ledger_v1_ledger_proto = out.File
	file_api_ledger_v1_ledger_proto_rawDesc = nil
	file_api_ledger_v1_ledger_proto_goTypes = nil
	file_api_ledger_v1_ledger_proto_depIdxs = nil
}
