// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/ledger/v1/ledger.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovementEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAccount *MovementEntry_FromAccount `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccountId string                     `protobuf:"bytes,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount      string                     `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// client_id is an identifier passed by the client so the client can find the ledger entry later on using this id.
	// Its up to the client whether they want to supply this id or not.
	ClientId string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *MovementEntry) Reset() {
	*x = MovementEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementEntry) ProtoMessage() {}

func (x *MovementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementEntry.ProtoReflect.Descriptor instead.
func (*MovementEntry) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *MovementEntry) GetFromAccount() *MovementEntry_FromAccount {
	if x != nil {
		return x.FromAccount
	}
	return nil
}

func (x *MovementEntry) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *MovementEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MovementEntry) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TransactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey  string           `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MovementEntries []*MovementEntry `protobuf:"bytes,2,rep,name=movement_entries,json=movementEntries,proto3" json:"movement_entries,omitempty"`
}

func (x *TransactRequest) Reset() {
	*x = TransactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactRequest) ProtoMessage() {}

func (x *TransactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactRequest.ProtoReflect.Descriptor instead.
func (*TransactRequest) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransactRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransactRequest) GetMovementEntries() []*MovementEntry {
	if x != nil {
		return x.MovementEntries
	}
	return nil
}

type TransactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// movement_id is a unqiue identifier for a transact/movement request. All movement entries requested in a single request
	// will be associated by this movement_id.
	MovementId string `protobuf:"bytes,1,opt,name=movement_id,json=movementId,proto3" json:"movement_id,omitempty"`
	// ledger_entries is entry per ledger row ordered with movement_entry in the transact request. But as one ledger row can only
	// contains of one account, one movement will be translated into two entries with the same client_id(if exist). For example:
	//
	// movement: from A to B for 200
	//
	// # Will be translated to
	//
	// ledger: ledger_id_a A -200 movement_client_id
	// ledger: ledger_id_b B 200 movement_client_id
	LedgerEntries []*TransactResponse_LedgerEntry `protobuf:"bytes,2,rep,name=ledger_entries,json=ledgerEntries,proto3" json:"ledger_entries,omitempty"`
	// ending_balances is the detailed balance changes and the ending state of the balance for each movement.
	// Please NOTE that ending_balances is not sorted and the client need to re-map the ending_balances per account id on their side.
	EndingBalances []*TransactResponse_Balance `protobuf:"bytes,3,rep,name=ending_balances,json=endingBalances,proto3" json:"ending_balances,omitempty"`
	// transact_time is the timestamp for the transaction which also the same with all created_at and updated_at values.
	// You can also use this field for the time balance updated.
	TransactTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=transact_time,json=transactTime,proto3" json:"transact_time,omitempty"`
}

func (x *TransactResponse) Reset() {
	*x = TransactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse) ProtoMessage() {}

func (x *TransactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse.ProtoReflect.Descriptor instead.
func (*TransactResponse) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *TransactResponse) GetMovementId() string {
	if x != nil {
		return x.MovementId
	}
	return ""
}

func (x *TransactResponse) GetLedgerEntries() []*TransactResponse_LedgerEntry {
	if x != nil {
		return x.LedgerEntries
	}
	return nil
}

func (x *TransactResponse) GetEndingBalances() []*TransactResponse_Balance {
	if x != nil {
		return x.EndingBalances
	}
	return nil
}

func (x *TransactResponse) GetTransactTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactTime
	}
	return nil
}

type MovementEntry_FromAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAccountId string `protobuf:"bytes,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	// include_child explicitly sums the amount of money in the main and child accounts. The behavior of the movement
	// will be determined by the main account(from_account_id). If the main account doesn't allow the balances to be < 0
	// then the movement will be rejected if the SUM of money is negative.
	IncludeChild bool `protobuf:"varint,2,opt,name=include_child,json=includeChild,proto3" json:"include_child,omitempty"`
}

func (x *MovementEntry_FromAccount) Reset() {
	*x = MovementEntry_FromAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovementEntry_FromAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementEntry_FromAccount) ProtoMessage() {}

func (x *MovementEntry_FromAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementEntry_FromAccount.ProtoReflect.Descriptor instead.
func (*MovementEntry_FromAccount) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MovementEntry_FromAccount) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *MovementEntry_FromAccount) GetIncludeChild() bool {
	if x != nil {
		return x.IncludeChild
	}
	return false
}

type TransactResponse_Balance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// account_id is the affected account_id for the balance output of the transaction.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// ledger_id is the new ledger_id for the new balance.
	LedgerId string `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	// new_balance is the latest balance after transaction.
	NewBalance string `protobuf:"bytes,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	// previous_balance is the previous locked balance before transaction is completed.
	PreviousBalance string `protobuf:"bytes,4,opt,name=previous_balance,json=previousBalance,proto3" json:"previous_balance,omitempty"`
	// previous_ledger_id is the ledger_id for the previous_balance.
	PreviousLedgerId string `protobuf:"bytes,5,opt,name=previous_ledger_id,json=previousLedgerId,proto3" json:"previous_ledger_id,omitempty"`
	// previous_movement is the movement_id for the previous balance.
	PreviousMovementId string `protobuf:"bytes,6,opt,name=previous_movement_id,json=previousMovementId,proto3" json:"previous_movement_id,omitempty"`
}

func (x *TransactResponse_Balance) Reset() {
	*x = TransactResponse_Balance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse_Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse_Balance) ProtoMessage() {}

func (x *TransactResponse_Balance) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse_Balance.ProtoReflect.Descriptor instead.
func (*TransactResponse_Balance) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TransactResponse_Balance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TransactResponse_Balance) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *TransactResponse_Balance) GetNewBalance() string {
	if x != nil {
		return x.NewBalance
	}
	return ""
}

func (x *TransactResponse_Balance) GetPreviousBalance() string {
	if x != nil {
		return x.PreviousBalance
	}
	return ""
}

func (x *TransactResponse_Balance) GetPreviousLedgerId() string {
	if x != nil {
		return x.PreviousLedgerId
	}
	return ""
}

func (x *TransactResponse_Balance) GetPreviousMovementId() string {
	if x != nil {
		return x.PreviousMovementId
	}
	return ""
}

type TransactResponse_LedgerEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LedgerId         string `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	ClientId         string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MovementSequence int32  `protobuf:"varint,3,opt,name=movement_sequence,json=movementSequence,proto3" json:"movement_sequence,omitempty"`
}

func (x *TransactResponse_LedgerEntry) Reset() {
	*x = TransactResponse_LedgerEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ledger_v1_ledger_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse_LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse_LedgerEntry) ProtoMessage() {}

func (x *TransactResponse_LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_ledger_v1_ledger_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse_LedgerEntry.ProtoReflect.Descriptor instead.
func (*TransactResponse_LedgerEntry) Descriptor() ([]byte, []int) {
	return file_api_ledger_v1_ledger_proto_rawDescGZIP(), []int{2, 1}
}

func (x *TransactResponse_LedgerEntry) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *TransactResponse_LedgerEntry) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TransactResponse_LedgerEntry) GetMovementSequence() int32 {
	if x != nil {
		return x.MovementSequence
	}
	return 0
}

var File_api_ledger_v1_ledger_proto protoreflect.FileDescriptor

var file_api_ledger_v1_ledger_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x67, 0x6f,
	0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x02, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x5e, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x67,
	0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x0d, 0x74, 0x6f, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xba,
	0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0b, 0x74, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x1a,
	0x62, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e,
	0x0a, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52,
	0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x68,
	0x69, 0x6c, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6d, 0x70,
	0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f,
	0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x5e, 0x0a, 0x10, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x0a, 0xba, 0x48, 0x07,
	0x92, 0x01, 0x04, 0x08, 0x01, 0x10, 0x64, 0x52, 0x0f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x9a, 0x05, 0x0a, 0x10, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x5d,
	0x0a, 0x0e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x5b, 0x0a,
	0x0f, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x67, 0x6f, 0x5f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0xf1, 0x01, 0x0a, 0x07,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x14, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x1a,
	0x74, 0x0a, 0x0b, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x10, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2d, 0x61, 0x73, 0x64, 0x2f, 0x67,
	0x6f, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_api_ledger_v1_ledger_proto_rawDescData = file_api_ledger_v1_ledger_proto_rawDesc
)

func file_api_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_api_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_api_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ledger_v1_ledger_proto_rawDescData)
	})
	return file_api_ledger_v1_ledger_proto_rawDescData
}

var file_api_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_ledger_v1_ledger_proto_goTypes = []any{
	(*MovementEntry)(nil),                // 0: go_example.api.ledger.v1.MovementEntry
	(*TransactRequest)(nil),              // 1: go_example.api.ledger.v1.TransactRequest
	(*TransactResponse)(nil),             // 2: go_example.api.ledger.v1.TransactResponse
	(*MovementEntry_FromAccount)(nil),    // 3: go_example.api.ledger.v1.MovementEntry.FromAccount
	(*TransactResponse_Balance)(nil),     // 4: go_example.api.ledger.v1.TransactResponse.Balance
	(*TransactResponse_LedgerEntry)(nil), // 5: go_example.api.ledger.v1.TransactResponse.LedgerEntry
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
}
var file_api_ledger_v1_ledger_proto_depIdxs = []int32{
	3, // 0: go_example.api.ledger.v1.MovementEntry.from_account:type_name -> go_example.api.ledger.v1.MovementEntry.FromAccount
	0, // 1: go_example.api.ledger.v1.TransactRequest.movement_entries:type_name -> go_example.api.ledger.v1.MovementEntry
	5, // 2: go_example.api.ledger.v1.TransactResponse.ledger_entries:type_name -> go_example.api.ledger.v1.TransactResponse.LedgerEntry
	4, // 3: go_example.api.ledger.v1.TransactResponse.ending_balances:type_name -> go_example.api.ledger.v1.TransactResponse.Balance
	6, // 4: go_example.api.ledger.v1.TransactResponse.transact_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_ledger_v1_ledger_proto_init() }
func file_api_ledger_v1_ledger_proto_init() {
	if File_api_ledger_v1_ledger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ledger_v1_ledger_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MovementEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TransactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TransactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MovementEntry_FromAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TransactResponse_Balance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ledger_v1_ledger_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TransactResponse_LedgerEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ledger_v1_ledger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_api_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_api_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_api_ledger_v1_ledger_proto = out.File
	file_api_ledger_v1_ledger_proto_rawDesc = nil
	file_api_ledger_v1_ledger_proto_goTypes = nil
	file_api_ledger_v1_ledger_proto_depIdxs = nil
}
